CREATE TABLE `work_order` (
  `work_order_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Table primary key',
  `work_order_number` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Work order number',
  `company_person_id` int unsigned DEFAULT NULL COMMENT 'Assigned company - references person.person_id',
  `internal_number` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Internal work order number (not used)',
  `description` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Description',
  `received_date` datetime DEFAULT NULL COMMENT 'When work order was received',
  `acknowledged_person_id` int unsigned DEFAULT '0' COMMENT 'Person who acknowledged work order',
  `expected_completion_date` date DEFAULT NULL COMMENT 'Expected completion date',
  `dispatched_to_person_id` int unsigned DEFAULT NULL COMMENT 'Person that work order was dispatched to - references person.person_id',
  `actual_completion_date` datetime DEFAULT NULL COMMENT 'Actual completion date',
  `completion_code` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Completion code',
  `estimated_time` int unsigned NOT NULL DEFAULT '0' COMMENT 'Estimated work time in minutes',
  `created_date` datetime DEFAULT NULL COMMENT 'Record created date',
  `modified_date` datetime DEFAULT NULL COMMENT 'Record last update date',
  `tracking_number` int unsigned NOT NULL DEFAULT '0' COMMENT 'Tracking number',
  `attention` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `trade` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Work order trade',
  `trade_type_id` int unsigned DEFAULT NULL COMMENT 'Work order trade type - references type.type_id',
  `request` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Request text',
  `not_to_exceed` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'NTE amount',
  `requested_completion_date` date DEFAULT NULL COMMENT 'Requested completion date',
  `instructions` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Instructions text',
  `fax_sender` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Fax sender',
  `fax_recipient` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Fax recipient',
  `fax_pages` tinyint DEFAULT '0' COMMENT 'Number of fax pages',
  `requested_by` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Requestor name',
  `phone` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Contact phone number',
  `email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Contact email address',
  `requested_date` date DEFAULT NULL COMMENT 'When work order was requested',
  `required_date` date DEFAULT NULL COMMENT 'Required date',
  `priority` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Priority name',
  `crm_priority_type_id` int unsigned DEFAULT NULL COMMENT 'Priority type - references type.type_id',
  `category` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Category name',
  `type` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Work order type (name)',
  `fin_loc` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Location number',
  `store_hours` varchar(40) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Store open hours',
  `shop` varchar(40) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Shop name',
  `fac_supv` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `wo_status_type_id` mediumint unsigned NOT NULL DEFAULT '542' COMMENT 'Status type - references type.type_id',
  `cancel_reason_type_id` int unsigned DEFAULT NULL COMMENT 'Reason type for canceled work order  - references type.type_id',
  `via_type_id` mediumint unsigned DEFAULT NULL COMMENT 'Source of the work order (e.g. email, import, scrub) - references type.type_id',
  `extended_date` datetime DEFAULT NULL COMMENT 'Work extended date',
  `extended_why` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Work extension reason',
  `invoice_id` int unsigned DEFAULT NULL COMMENT 'Assigned invoice - references invoice.invoice_id',
  `invoice_amount` decimal(7,2) DEFAULT NULL COMMENT 'Invoice amount',
  `costs` decimal(7,2) DEFAULT NULL COMMENT 'Costs amount',
  `locked_id` mediumint unsigned NOT NULL DEFAULT '0' COMMENT 'Person that is currently locking work order for update - references person.person_id',
  `pickup_id` mediumint unsigned NOT NULL DEFAULT '0' COMMENT 'Person who picked up work order - references person.person_id',
  `shop_address_id` mediumint unsigned DEFAULT NULL COMMENT 'Assigned location (address) - references address.address_id',
  `acknowledged` tinyint DEFAULT '0' COMMENT 'Whether acknowledged',
  `invoice_status_type_id` mediumint unsigned NOT NULL DEFAULT '539' COMMENT 'Assigned invoice status type - references type.type_id',
  `bill_status_type_id` mediumint unsigned NOT NULL DEFAULT '585' COMMENT 'Assigned bill status type - references type.type_id',
  `creator_person_id` int NOT NULL DEFAULT '0' COMMENT 'Creator person - references person.person_id',
  `quote_status_type_id` mediumint unsigned DEFAULT NULL COMMENT 'Assigned quote status type - references type.type_id',
  `invoice_number` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Assigned invoice number',
  `project_manager_person_id` int unsigned DEFAULT NULL COMMENT 'Assigned project manager - references person.person_id',
  `scheduled_date` datetime DEFAULT NULL COMMENT 'Scheduled date',
  `authorization_code` varchar(24) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Authorization code',
  `requested_by_person_id` int unsigned DEFAULT NULL COMMENT 'Requestor person - references person.person_id',
  `billing_company_person_id` int DEFAULT NULL COMMENT 'Assigned billing company - references person.person_id',
  `customer_setting_id` int DEFAULT '0' COMMENT 'Assigned customer settings - references customer_settings.customer_settings_id',
  `client_status` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Status from client''s system',
  `client_ecd` datetime DEFAULT NULL COMMENT 'Expected completion date from client''s system',
  `parts_status_type_id` mediumint unsigned DEFAULT NULL COMMENT 'Parts status type - references type.type_id',
  `supplier_person_id` int unsigned DEFAULT NULL COMMENT 'Assigned supplier - references person.person_id',
  `purchase_order` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Purchase order number',
  `work_performed` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Work performed text',
  `external_id` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'External systems ID''s',
  `service_category_type_id` int DEFAULT NULL COMMENT 'Service category type - references type.type_id',
  `satisfaction_confirmation` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Satisfaction confirmation text',
  `client_cause_remedy_options` text CHARACTER SET latin1 COLLATE latin1_swedish_ci COMMENT 'Cause/remedy options from client''s FM Pilot 2 system (JSON string)',
  `client_cause` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Cause from client''s FM Pilot 2 system',
  `client_remedy` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Remedy from client''s FM Pilot 2 system',
  `owner_person_id` int unsigned DEFAULT NULL COMMENT 'Owner company - references person.person_id',
  `wo_type_id` int unsigned DEFAULT NULL COMMENT 'Work order type - references type.type_id',
  `sampro_work_order_id` char(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Work order ID from Sampro system',
  `survey_id` int unsigned DEFAULT NULL COMMENT 'Assigned survey - references survey.survey_id',
  `required_arrival_time` datetime DEFAULT NULL COMMENT 'Required tech arrival time',
  `tech_trade_type_id` int DEFAULT NULL COMMENT 'Tech trade type - references type.type_id',
  `work_type` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT 'Work type name',
  `equipment_needed` varchar(255) DEFAULT NULL,
  `equipment_needed_text` varchar(255) DEFAULT NULL,
  `target_visit_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`work_order_id`),
  KEY `invoice_amount` (`invoice_amount`),
  KEY `costs` (`costs`),
  KEY `company_person_id` (`company_person_id`),
  KEY `created_date` (`created_date`),
  KEY `bill_status` (`bill_status_type_id`),
  KEY `received_date_i` (`received_date`),
  KEY `crm_priority_type_id` (`crm_priority_type_id`),
  KEY `cancel_reason_type_id` (`cancel_reason_type_id`),
  KEY `creator_person_id` (`creator_person_id`),
  KEY `wo_number_received_i` (`work_order_number`,`received_date`),
  KEY `billing_company_id_i` (`billing_company_person_id`),
  KEY `client_status_i` (`client_status`(128)),
  KEY `quote_status_type_id_i` (`quote_status_type_id`),
  KEY `shop_and_status` (`shop_address_id`,`wo_status_type_id`),
  KEY `status_number` (`work_order_number`,`wo_status_type_id`),
  KEY `via_type_id_i` (`via_type_id`),
  KEY `wo_status_type_id` (`wo_status_type_id`),
  KEY `invoice_status` (`invoice_status_type_id`,`wo_status_type_id`),
  KEY `parts_status_type_id` (`parts_status_type_id`),
  KEY `sampro_work_order_id` (`sampro_work_order_id`),
  KEY `shop_address_id` (`shop_address_id`),
  KEY `expected_completion_date_i` (`expected_completion_date`),
  KEY `owner_person_id_i` (`owner_person_id`),
  KEY `acknowledged_person_id_i` (`acknowledged_person_id`),
  KEY `actual_completion_date` (`actual_completion_date`),
  KEY `dispatched_to_person_id_i` (`dispatched_to_person_id`),
  KEY `project_manager_person_id_i` (`project_manager_person_id`),
  KEY `requested_by_person_id_i` (`requested_by_person_id`),
  KEY `supplier_person_id_i` (`supplier_person_id`),
  KEY `fin_loc` (`fin_loc`),
  KEY `internal_number` (`internal_number`),
  KEY `work_order_idx_id_number` (`work_order_id`,`work_order_number`)
) ENGINE=InnoDB